### ISSUE TITLE
No instruction for building

### ISSUE THREAD

**Issue by ghaspias** [tsoding/Noq#14]
Hi,
For those who are not familiar with rust, can you provide instructions for compilation of Noq, especially under Windows?
I am getting an error when running `cargo build`:

> note: LINK : fatal error LNK1181: cannot open input file 'advapi32.lib'

When running `rustc main.rs`, I get an error regarding termion:

> error[E0433]: failed to resolve: maybe a missing crate `termion`?

Thanks.

**Comment by wiebecommajonas** [comment]
Seems to be a broken SDK (see [this issue](https://github.com/rust-lang/rust/issues/43039)).

In any case, this crate does not run on windows as is. See #8 for more information.

**Comment by Piturnah** [comment]
Hiya, not the maintainer but, this crate is using [termion](https://crates.io/crates/termion) which is a crate for ANSI terminals only.

It was probably chosen primarily for its small size and convenient API, but there is another - larger - crate [crossterm](https://crates.io/crates/crossterm) providing the same functionality in a cross-platform way.

The maintainer uses Debian Linux and (while I of course can't speak for him) I think is unlikely to switch to crossterm but maybe someone could open a PR or a fork since the changes are fairly trivial to make. e.g. [newdoku](https://github.com/Piturnah/newdoku/commit/e2222f6c13d784b0be37bbb3eda6ce2ebf88e6ec)

**Comment by Piturnah** [comment]
Fixed in #15
